[workspace]
resolver = "2"
members = [
    "account",
    "contracts",
    "controller",
    "swap-intent",
    "swap-ft-intent",
    "tests",
]
default-members = ["contracts"]

[workspace.package]
edition = "2021"

[workspace.dependencies]
defuse-account-contract.path = "./account"
defuse-contracts = { path = "./contracts", default-features = false }
defuse-controller-contract.path = "./controller"
defuse-swap-intent-contract.path = "./swap-intent"
defuse-swap-ft-intent-contract.path = "./swap-ft-intent"

anyhow = "1"
lazy_static = "1.4"
near-contract-standards = "5.1.0"
near-sdk = "5.1"
near-workspaces = "0.10"
serde_json = "1"
thiserror = "1"
tokio = { version = "1.38", default-features = false }

[workspace.lints.clippy]
all = "deny"
nursery = "deny"
pedantic = "deny"
module_name_repetitions = "allow"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
strip = "symbols"
panic = "abort"
overflow-checks = true

# TODO: remove when near-sdk 6.0.0 is released:
# https://github.com/near/near-sdk-rs/pull/1192
[patch.crates-io.near-contract-standards]
git = "https://github.com/near/near-sdk-rs"
[patch.crates-io.near-sdk]
git = "https://github.com/near/near-sdk-rs"
