[workspace]
resolver = "2"
members = ["account", "controller", "intent", "tests"]

[workspace.package]
edition = "2021"

[workspace.dependencies]
defuse-account-contract.path = "./account"

anyhow = "1"
near-sdk = "5.1"
near-workspaces = "0.10"
serde_json = "1"
tokio = { version = "1.37", default-features = false }

[workspace.dependencies.near-plugins]
git = "https://github.com/near-one/near-plugins"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
