[workspace]
resolver = "2"
members = [
    "account",
    "account-impl",
    "contracts",
    "controller",
    "controller-impl",
    "intent",
    "intent-impl",
    "tests",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
defuse-account-contract.path = "./account"
defuse-account-contract-impl.path = "./account-impl"
defuse-contracts.path = "./contracts"
defuse-controller-contract.path = "./controller"
defuse-controller-contract-impl.path = "./controller-impl"
defuse-intent-contract.path = "./intent"
defuse-intent-contract-impl.path = "./intent-impl"

near-sdk = "5.1"
near-workspaces = "0.10"
near-contract-standards = "5.1.0"

anyhow = "1"
lazy_static = "1.4"
serde_json = "1"
strum = { version = "0.26", features = ["derive"] }
tokio = { version = "1.38", default-features = false }


[workspace.lints.clippy]
all = "deny"
nursery = "deny"
pedantic = "deny"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
strip = "symbols"
panic = "abort"
overflow-checks = true
