[workspace]
resolver = "2"
members = ["account", "contracts", "controller", "intent", "tests"]
default-members = ["contracts"]

[workspace.package]
edition = "2021"

[workspace.dependencies]
defuse-account-contract.path = "./account"
defuse-contracts = { path = "./contracts", default-features = false }
defuse-controller-contract.path = "./controller"
defuse-intent-contract.path = "./intent"

anyhow = "1"
lazy_static = "1.4"
near-contract-standards = "5.1.0"
near-sdk = "5.1"
near-workspaces = "0.10"
serde_json = "1"
thiserror = "1"
tokio = { version = "1.38", default-features = false }

[workspace.lints.clippy]
all = "deny"
nursery = "deny"
pedantic = "deny"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
strip = "symbols"
panic = "abort"
overflow-checks = true
