[workspace.package]
edition = "2021"

[workspace.dependencies]
anyhow = "1"
near-sdk = "5.1"
near-workspaces = "0.10"
serde_json = "1"
tokio = { version = "1.38", default-features = false }

[workspace]
resolver = "2"
members = [
    "account",
    "controller",
    "intent",
    "tests"
]

[workspace.lints.clippy]
all = "deny"
nursery = "deny"
pedantic = "deny"
module_name_repetitions = "allow"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
