[config]
default_to_workspace = false
skip_core_tasks = true

[env]
TARGET_DIR = "${PWD}/res"

[tasks.default]
alias = "build"

[tasks.clippy]
command = "cargo"
dependencies = ["build"]
args = ["clippy", "--workspace", "--all-targets"]

[tasks.build]
dependencies = [
    "build-account",
    "build-swap-intent",
    "build-swap-ft-intent",
    "build-controller",
    "contract-stats",
]


[tasks.build-account]
command = "cargo"
args = [
    "near",
    "build",
    "--manifest-path",
    "./account/Cargo.toml",
    "--out-dir",
    "${TARGET_DIR}",
    "--no-docker",
    "--no-embed-abi",
]

[tasks.build-swap-intent]
command = "cargo"
args = [
    "near",
    "build",
    "--manifest-path",
    "./intents/swap/Cargo.toml",
    "--out-dir",
    "${TARGET_DIR}",
    "--no-docker",
    "--no-embed-abi",
]

[tasks.build-swap-ft-intent]
command = "cargo"
args = [
    "near",
    "build",
    "--manifest-path",
    "./intents/swap-ft/Cargo.toml",
    "--out-dir",
    "${TARGET_DIR}",
    "--no-docker",
    "--no-embed-abi",
]

[tasks.build-controller]
command = "cargo"
args = [
    "near",
    "build",
    "--manifest-path",
    "./controller/Cargo.toml",
    "--out-dir",
    "${TARGET_DIR}",
    "--no-docker",
    "--no-embed-abi",
]

[tasks.test]
alias = "tests"

[tasks.tests]
dependencies = ["build"]
command = "cargo"
args = ["test", "--workspace", "--all-targets", "${@}"]

[tasks.clean]
dependencies = ["rm-contracts"]
command = "cargo"
args = ["clean"]

[tasks.rm-contracts]
script = "rm -rf ${TARGET_DIR}"

[tasks.contract-stats]
category = "Tools"
script = "cd ${TARGET_DIR} && du -ah *.wasm"
