[package]
name = "defuse-contracts"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[dependencies]
near-sdk.workspace = true
near-contract-standards.workspace = true
thiserror.workspace = true

[features]
default = ["account", "controller", "intent", "mpc"]
account = []
controller = []
intent = []
mpc = []
