[package]
name = "defuse-contracts"
version = "0.1.0"
edition.workspace = true

[dependencies]
defuse-account-contract.workspace = true
defuse-controller-contract.workspace = true
defuse-intent-contract.workspace = true
