[package]
name = "defuse-controller-contract"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
# defuse-account-contract.workspace = true

near-sdk.workspace = true
near-plugins.workspace = true
