name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    needs: fmt
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          # this action doesn't allow passing `shared-key` to Swatinem/rust-cache,
          # so we setup cache manually in the next step
          cache: false
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ github.ref }}
      - name: Install cargo-make
        run: cargo install cargo-make
      - name: Run clippy
        run: cargo make clippy

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: clippy
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          # this action doesn't allow passing `shared-key` to Swatinem/rust-cache,
          # so we setup cache manually in the next step
          cache: false
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ github.ref }}
      - name: Install cargo-make
        run: cargo install cargo-make
      - name: Build
        run: cargo make build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: res
          path: ./res/

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          # this action doesn't allow passing `shared-key` to Swatinem/rust-cache,
          # so we setup cache manually in the next step
          cache: false
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ github.ref }}
      - name: Install cargo-make
        run: cargo install cargo-make
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: res
      - name: Run Tests
        run: cargo make tests
